// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewtonServices.Data;

#nullable disable

namespace NewtonServices.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20260615162712_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewtonServices.Models.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("690ddf28-b89d-4d73-845a-61a3fe97d231"),
                            Code = "SPO",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sport"
                        },
                        new
                        {
                            Id = new Guid("38c82dc7-0baa-4981-b620-841fc7d4076a"),
                            Code = "ACT",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("ac0a73cb-b745-4889-86db-8bd5a0712cd3"),
                            Code = "SHT",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Shooter"
                        },
                        new
                        {
                            Id = new Guid("b7fd6b7d-b307-404a-94ac-c908359adbe0"),
                            Code = "ADV",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Adventure"
                        });
                });

            modelBuilder.Entity("NewtonServices.Models.Entities.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0c85b57f-643c-4176-9e1b-48a17d03ea7e"),
                            Code = "PS",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PlayStation"
                        },
                        new
                        {
                            Id = new Guid("55bd7dd8-c9f1-4745-a7a6-c4509a82be67"),
                            Code = "XBX",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Xbox"
                        },
                        new
                        {
                            Id = new Guid("3c8ccba5-b0d7-45cd-8072-c5876f0593dc"),
                            Code = "PC",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PC"
                        });
                });

            modelBuilder.Entity("NewtonServices.Models.Entities.VideoGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("PlatformId");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3134f924-ca72-4a1e-a5bd-3f86e15fd937"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = new Guid("690ddf28-b89d-4d73-845a-61a3fe97d231"),
                            IsAvailable = false,
                            PlatformId = new Guid("0c85b57f-643c-4176-9e1b-48a17d03ea7e"),
                            Price = 59.99m,
                            Quantity = 10,
                            Title = "Game 1"
                        },
                        new
                        {
                            Id = new Guid("a345f2da-75ed-4f30-9fd3-1cad0f7500c7"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = new Guid("38c82dc7-0baa-4981-b620-841fc7d4076a"),
                            IsAvailable = false,
                            PlatformId = new Guid("55bd7dd8-c9f1-4745-a7a6-c4509a82be67"),
                            Price = 49.99m,
                            Quantity = 10,
                            Title = "Game 2"
                        },
                        new
                        {
                            Id = new Guid("18e12425-b124-4e3d-b88c-8312c3b370be"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = new Guid("b7fd6b7d-b307-404a-94ac-c908359adbe0"),
                            IsAvailable = false,
                            PlatformId = new Guid("3c8ccba5-b0d7-45cd-8072-c5876f0593dc"),
                            Price = 69.99m,
                            Quantity = 10,
                            Title = "Game 3"
                        },
                        new
                        {
                            Id = new Guid("f73166ab-47f1-47b9-8e15-a94f7b0ed216"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = new Guid("690ddf28-b89d-4d73-845a-61a3fe97d231"),
                            IsAvailable = false,
                            PlatformId = new Guid("0c85b57f-643c-4176-9e1b-48a17d03ea7e"),
                            Price = 69.99m,
                            Quantity = 10,
                            Title = "Game 4"
                        },
                        new
                        {
                            Id = new Guid("8c80d238-8ab2-48b1-9cde-2a2e1a826731"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = new Guid("b7fd6b7d-b307-404a-94ac-c908359adbe0"),
                            IsAvailable = false,
                            PlatformId = new Guid("3c8ccba5-b0d7-45cd-8072-c5876f0593dc"),
                            Price = 69.99m,
                            Quantity = 10,
                            Title = "Game 5"
                        });
                });

            modelBuilder.Entity("NewtonServices.Models.Views.VwAllVideoGames", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenreCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlatformCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.ToView("VwAllVideoGames", (string)null);
                });

            modelBuilder.Entity("NewtonServices.Models.Entities.VideoGame", b =>
                {
                    b.HasOne("NewtonServices.Models.Entities.Genre", "Genre")
                        .WithMany("VideoGames")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NewtonServices.Models.Entities.Platform", "Platform")
                        .WithMany("VideoGames")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("NewtonServices.Models.Entities.Genre", b =>
                {
                    b.Navigation("VideoGames");
                });

            modelBuilder.Entity("NewtonServices.Models.Entities.Platform", b =>
                {
                    b.Navigation("VideoGames");
                });
#pragma warning restore 612, 618
        }
    }
}
